Sign your code
cloudx-labs/posts pull request #30
Opened 2022-04-11 14:30 UTC by navarroaxel

2022-04-11 17:42 UTC, pabloromeo requested changes

2022-04-11 17:42 UTC, pabloromeo commented on posts/navarroaxel/01.sign-your-code.md
> +Did you know you can sign your code in Git using a GPG key? A lot of programmers don't know they can sign their Git commits using a signature created by themself.
```suggestion
Did you know you can sign your code in Git using a GPG key? A lot of programmers don't know they can sign their Git commits using a signature created by themselves.
```

2022-04-11 17:42 UTC, pabloromeo commented on posts/navarroaxel/01.sign-your-code.md
> +In the other hand, some Linux distros, like Arch Linux, uses Arch User (Git) Repositories made by users to build non-official supported packages. I mean, if you're compiling and installing a package
```suggestion
On the other hand, some Linux distros, like Arch Linux, uses Arch User (Git) Repositories made by users to build non-official supported packages. I mean, if you're compiling and installing a package via another user's instructions maybe you like the idea of the authors signing their work. ⚠️
```

2022-04-11 18:33 UTC, pabloromeo submitted a review, later dismissed
If you want, you could add an image showing the green checkmarks from signed commits.

2022-05-23 16:55 UTC, pabloromeo requested changes

2022-05-23 16:55 UTC, pabloromeo commented on posts/navarroaxel/03.sign-your-code.md
> +You can create a GPG key following [this guide](https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key) in GitHub, remember that you should register
```suggestion
You can create a GPG key following [this guide](https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key) in GitHub. Remember that you should register it in [GitHub](https://github.com/settings/keys), or [GitLab](https://gitlab.com/-/profile/gpg_keys).
```

2022-05-23 17:01 UTC, pabloromeo approved these changes

2022-05-24 18:15 UTC, EzequielMontel approved these changes

2022-05-24 18:25 UTC, merged