post: a Well-Known change password
cloudx-labs/posts pull request #34
Opened 2022-04-25 16:16 UTC by navarroaxel

2022-04-25 16:54 UTC, pabloromeo requested changes
Suggested typo fixes and syntax

2022-04-25 16:54 UTC, pabloromeo commented on posts/navarroaxel/02.well-known-change-password.md
> +We can programmatically advertise where a user can change its password, improving the **security** and **usability** of a website that requires authentication.
```suggestion
We can programmatically advertise where a user can change their password, improving the **security** and **usability** of a website that requires authentication.
```

2022-04-25 16:54 UTC, pabloromeo commented on posts/navarroaxel/02.well-known-change-password.md
> +Now you can create a semantic HTML form for change passwords and the password manager tool will make the rest.
```suggestion
Now you can create a semantic HTML form for changing passwords and the password manager tool will do the rest.
```

2022-04-25 16:54 UTC, pabloromeo commented on posts/navarroaxel/02.well-known-change-password.md
> +Let's check how this works. 💪
```suggestion
Let's see how this works. 💪
```

2022-04-25 16:57 UTC, navarroaxel commented on posts/navarroaxel/02.well-known-change-password.md
> +The [specification](https://w3c.github.io/webappsec-change-password-url/) for Well-Known URLs for Change passwords are still in draft, but we can found examples in popular websites like [GitHub](http
:thinking: but `Change password` is the feature name. Perhaps this better:
```suggestion
The [specification](https://w3c.github.io/webappsec-change-password-url/) for Well-Known Change Password URL is still in draft, but we can found examples in popular websites like [GitHub](https://github.com/.well-known/change-password), [Slack](https://slack.com/.well-known/change-password), or [Wikipedia](https://wikipedia.org/.well-known/change-password).
```

2022-04-25 16:59 UTC, pabloromeo commented on posts/navarroaxel/02.well-known-change-password.md
> +The [specification](https://w3c.github.io/webappsec-change-password-url/) for Well-Known URLs for Change passwords are still in draft, but we can found examples in popular websites like [GitHub](http
Ah, then yes, that's better.

2022-05-09 16:11 UTC, frangeris approved these changes

2022-05-09 16:32 UTC, merged