feat/automapper post
cloudx-labs/posts pull request #35
Opened 2022-04-27 00:18 UTC by ilaborde

2022-04-28 14:29 UTC, navarroaxel commented on posts/ilaborde/1.automapper.md
> +published: false
Set to `true` to publish on merge
```suggestion
published: true
```

2022-04-28 14:35 UTC, navarroaxel commented on posts/ilaborde/1.automapper.md
> +When querying data with Entity Framework is very common to query data using the Include method, and then manually map the collection of posts to a collection of PostDto:
```suggestion
When querying data with Entity Framework is very common to query data using the Include method, and then manually map the collection of posts to a collection of `PostDto`:
```

2022-04-28 14:36 UTC, navarroaxel commented on posts/ilaborde/1.automapper.md
> +_The .ProjectTo<PostDto>() will tell AutoMapper’s mapping engine to emit a select clause to the IQueryable that will inform Entity Framework that it only needs to query the fields presents in the DTO
```suggestion
_The `.ProjectTo<PostDto>()` will tell AutoMapper’s mapping engine to emit a select clause to the IQueryable that will inform Entity Framework that it only needs to query the fields presents in the DTO._
```

2022-04-28 14:36 UTC, navarroaxel commented on posts/ilaborde/1.automapper.md
> +And writing again only 1 C# line:
Sounds better?
```suggestion
And writing again only 1 line on C#:
```

2022-04-28 14:37 UTC, navarroaxel commented on posts/ilaborde/1.automapper.md
> +---
Rename file to `01.automapper.md` to have a good order when you have more than 9 posts in the future.

2022-04-28 15:54 UTC, navarroaxel commented on posts/ilaborde/01.automapper.md
> +      .ToListAsync();
```suggestion
var posts = dbContext.Posts
    .Include(x => x.Blog)
    .Include(x => x.Comments)
    .ToListAsync();
```

2022-04-28 15:54 UTC, navarroaxel commented on posts/ilaborde/01.automapper.md
> +   var posts = mapper.ProjectTo<PostDto>(dbContext.Posts, null).ToListAsync();
```suggestion
 var posts = mapper.ProjectTo<PostDto>(dbContext.Posts, null).ToListAsync();
```

2022-04-28 15:54 UTC, navarroaxel commented on posts/ilaborde/01.automapper.md
> +    }
```suggestion
public class PostSummaryDto
{
    public int Id { get; set; }
    public string Title { get; set; }
    public int CommentsCount { get; set; }
}
```

2022-04-28 15:54 UTC, navarroaxel commented on posts/ilaborde/01.automapper.md
> +    var postSummary = mapper.ProjectTo<PostSummaryDto>(dbContext.Posts, null).ToListAsync();
```suggestion
var postSummary = mapper.ProjectTo<PostSummaryDto>(dbContext.Posts, null).ToListAsync();
```

2022-04-28 15:54 UTC, navarroaxel commented on posts/ilaborde/01.automapper.md
> +title: EF Core Simplify your queries with AutoMapper
```suggestion
title: Entity Framework: Simplify your queries with AutoMapper
```

2022-04-28 15:54 UTC, navarroaxel commented on posts/ilaborde/01.automapper.md
> +---
```suggestion
id: 701321
---
```

2022-04-28 17:31 UTC, pabloromeo requested changes

2022-04-28 17:31 UTC, pabloromeo commented on posts/ilaborde/01.automapper.md
> +
An introduction is missing, in order to give context to the reader

2022-04-28 17:31 UTC, pabloromeo commented on posts/ilaborde/01.automapper.md
> +### ProjectTO to the rescue
It says "to the rescue" of some problem, but the problem was never actually mentioned. For example, in the first query you show, you probably want to mention that full entities are meterialized, including properties you might not even need.
The second alternative with a manual projection would solve that, but what problems does it have using it that way? THAT is what projecTo solves and justifies the "to the rescue".

2022-04-28 17:31 UTC, pabloromeo commented on posts/ilaborde/01.automapper.md
> +    var post = dbContext.Posts
```suggestion
    var post = await dbContext.Posts
```

2022-04-28 17:31 UTC, pabloromeo commented on posts/ilaborde/01.automapper.md
> +   var posts = mapper.ProjectTo<PostDto>(dbContext.Posts, null).ToListAsync();
```suggestion
   var posts = await mapper.ProjectTo<PostDto>(dbContext.Posts, null).ToListAsync();
```

2022-04-28 17:31 UTC, pabloromeo commented on posts/ilaborde/01.automapper.md
> +AutoMapper has a simple way to solve this:
The more common usage is applying it as an extension method to an IQueriable.

2022-04-28 17:31 UTC, pabloromeo commented on posts/ilaborde/01.automapper.md
> +   var posts = mapper.ProjectTo<PostDto>(dbContext.Posts, null).ToListAsync();
```suggestion
   var posts = await mapper.ProjectTo<PostDto>(dbContext.Posts, null).ToListAsync();
```

2022-04-29 19:19 UTC, navarroaxel commented on posts/ilaborde/01.automapper.md
> +For the examples of code, we are going to use the following entities.
```suggestion
For the examples of code, we are going to use the following entities:
```

2022-04-29 19:19 UTC, navarroaxel commented on posts/ilaborde/01.automapper.md
> +And DTOs
Same punctuation like above
```suggestion
And DTOs:
```

2022-04-29 19:19 UTC, navarroaxel commented on posts/ilaborde/01.automapper.md
> +// map to DTO
```suggestion
// map to DTO
```

2022-04-29 19:19 UTC, navarroaxel commented on posts/ilaborde/01.automapper.md
> +[c].[Id], [c].[Content], [c].[PostId]
```suggestion
    [c].[Id], [c].[Content], [c].[PostId]
```

2022-04-29 19:19 UTC, navarroaxel commented on posts/ilaborde/01.automapper.md
> +A common case for the `ProjectTo` is using small DTOs/models. For example, we can have a smaller DTO to just return a summary of the posts to list in the frontend, with just the id, name, and comment
```suggestion
A common case for the `.ProjectTo` is using small DTOs/models. For example, we can have a smaller DTO to just return a summary of the posts to list in the frontend, with just the id, name, and comments counts. 
```

2022-04-29 19:19 UTC, navarroaxel commented on posts/ilaborde/01.automapper.md
> +    WHERE [p].[Id] = [c].[PostId]) AS [CommentsCount]
It's hard to read when the sub-select ends
```suggestion
        SELECT COUNT(*)
        FROM [Comments] AS [c]
        WHERE [p].[Id] = [c].[PostId]
    ) AS [CommentsCount]
```

2022-04-29 20:57 UTC, pabloromeo approved these changes

2022-04-29 21:01 UTC, navarroaxel approved these changes

2022-04-29 23:10 UTC, merged