post: revoke apple id
cloudx-labs/posts pull request #49
Opened 2022-07-18 01:33 UTC by Nacho-source

2022-07-19 19:22 UTC, navarroaxel commented on posts/Nacho-source/01.Revoking-Apple-Token.md
> +const makeJWT = () => {
```suggestion
const makeJWT = async () => {
```

2022-07-19 19:30 UTC, navarroaxel commented on posts/Nacho-source/01.Revoking-Apple-Token.md
> +published: false
Use `true` to publish when is merged
```suggestion
published: true
```

2022-07-19 21:04 UTC, pabloromeo requested changes

2022-07-19 21:04 UTC, pabloromeo commented on posts/Nacho-source/01.Revoking-Apple-Token.md
> +In the past few weeks, an issue has been causing some headaches amongst the mobile developers community. By the end of May, [Apple has announced](https://developer.apple.com/news/?id=12m75xbj) that e
```suggestion
In the past few weeks, an issue has been causing some headaches amongst the mobile developers community. By the end of May, [Apple has announced](https://developer.apple.com/news/?id=12m75xbj) that every new version of apps published in App Store that allow users to sign in through Apple IDs also must allow them to cancel their subscription through the use of a [specific API](https://developer.apple.com/documentation/sign_in_with_apple/revoke_tokens). The app versions that don't implement this requirement will neither pass the review nor be available for use.
```

2022-07-19 21:04 UTC, pabloromeo commented on posts/Nacho-source/01.Revoking-Apple-Token.md
> +> ❗Part of the problem is that the use of this API does not guarantee the effective disassociation between your app and the Apple ID -which is logically the pursued objective, even when it returns _2
```suggestion
> ❗Part of the problem is that the use of this API does not guarantee the effective disassociation between your app and the Apple ID -which is logically the pursued objective, even when it returns _200_ (and no other significant info). Leaving that aside, this workaround does the job as it satisfies the required behavior. The rest is Apple’s problem.
```

2022-07-19 21:04 UTC, pabloromeo commented on posts/Nacho-source/01.Revoking-Apple-Token.md
> +Although I am using [_React Native_](https://reactnative.dev), this solution should work globally if you can access the `identityToken` every time the user enters the app, either signing or loging in
```suggestion
Although I am using [_React Native_](https://reactnative.dev), this solution should work globally if you can access the `identityToken` every time the user enters the app, either signing or logging in.
```

2022-07-21 17:34 UTC, pabloromeo approved these changes

2022-07-24 19:34 UTC, navarroaxel commented on posts/nachoSource/01.revoking-apple-token.md
> +
```suggestion
```

2022-07-24 19:34 UTC, navarroaxel commented on posts/nachoSource/01.revoking-apple-token.md
> +    );
```suggestion
    );
    
    const {refresh_token} = await authTokenResponse.json();
```

2022-07-24 19:34 UTC, navarroaxel commented on posts/nachoSource/01.revoking-apple-token.md
> +            token: authTokenResponse.data.refresh_token,
```suggestion
            token: refresh_token,
```

2022-07-24 19:34 UTC, navarroaxel commented on posts/nachoSource/01.revoking-apple-token.md
> +    });
```suggestion
    const response = await fetch('https://appleid.apple.com/auth/revoke', {
        method: "POST",
        body: JSON.stringify({
            client_id: YOUR_CLIENT_ID,
            client_secret: clientSecret,
            token: identityToken,
        }),
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
    });
    
    return response.json()
```

2022-07-25 19:41 UTC, pabloromeo approved these changes

2022-07-25 19:43 UTC, pabloromeo requested changes

2022-07-25 19:43 UTC, pabloromeo commented on posts/nachoSource/01.revoking-apple-token.md
> +cover_image: ./assets/app-store.jpeg
```suggestion
cover_image: ./assets/app-store.png
```

2022-07-27 10:18 UTC, navarroaxel commented on posts/nachoSource/01.revoking-apple-token.md
> +const revokeToken = (identityToken) => {
```suggestion
const revokeToken = async (identityToken) => {
```

2022-07-27 17:47 UTC, pabloromeo approved these changes

2023-04-17 16:49 UTC, closed without merging